require: rubocop-rspec

inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundArguments:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Metrics/LineLength:
  Max: 120

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '()'
    '%i': '[]'
    '%I': '[]'
    '%r': '()'
    '%w': '[]'
    '%W': '[]'
